### ISSUE TITLE
Ansible - use handlers for restarting nginx (only if necessary)

### ISSUE THREAD

**Issue by pmauduit** [qgis/QGIS-Sysadmin#25]
See https://github.com/qgis/QGIS-Sysadmin/pull/24 (section "Playbook is not idempotent"): One could use the handler mechanisms described onto https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#handlers-running-operations-on-change instead of launching a "service nginx restart" (or equivalent) regardless of if something actually changed or not.

**Comment by pmauduit** [comment]
to integrate Yves Jacolin's work on the ms_perfs camptocamp project (https://github.com/camptocamp/ms_perfs), I used the handlers to restart nginx if necessary, see https://github.com/pmauduit/QGIS-Sysadmin/blob/integrate-msperf/qgis4/ansible/roles/msperfs/handlers/main.yml and https://github.com/pmauduit/QGIS-Sysadmin/blob/integrate-msperf/qgis4/ansible/roles/msperfs/tasks/main.yml#L94

**Comment by elemoine** [comment]
Yes using handlers is the way to go! Let's add that. @pmauduit can you work on a PR?

**Comment by pmauduit** [comment]
sure

**Comment by pmauduit** [comment]
I've got a concern about nginx especially: the base role takes care of installing nginx, but other roles are expecting it to be installed. This won't probably never be the case, but that means that we cannot use the other roles alone (e.g. using a tag as @elemoine introduced them).

We might want to copy the task from base in every other concerned roles:

```
- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
```

**Comment by elemoine** [comment]
> We might want to copy the task from base in every other concerned roles:

We'd also need to copy the nginx handler(s).

I'd suggest that we create an nginx role and make it a dependency of the roles that rely on nginx.

**Comment by pmauduit** [comment]
Right, I'll adapt.

**Comment by pmauduit** [comment]
updated: https://github.com/qgis/QGIS-Sysadmin/pull/29/files
